version: '3.8'

services:
  flask-app:
    build: .
    ports:
      - "3500:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - FLASK_APP=app.py
    command: flask run --host=0.0.0.0 --port=5000 --reload